-- Run this script in your Supabase SQL editor to create the necessary table

CREATE TABLE IF NOT EXISTS public.summaries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL,
    transcript TEXT,
    summary JSONB NOT NULL,
    language TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Protect against accidental modifications if needed
-- ALTER TABLE public.summaries ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Allow anonymous inserts" ON public.summaries FOR INSERT TO anon WITH CHECK (true);
-- CREATE POLICY "Allow anonymous selects" ON public.summaries FOR SELECT TO anon USING (true);
